app: cloud-monitor
serve:
  port: 8080
  debug: true
#  read_timeout:
#  write_timeout:
db:
  url: (127.0.0.1:3306)/cloud_monitor_manager?charset=utf8mb4&parseTime=True&loc=Local
  dialect: mysql
  max_idle_connes: 10
  max_open_connes: 100
  username: root

logger:
  data_log_prefix: /logs/
  service_name: cloud-monitor
  max_size:
  max_backups:
  max_age:
  compress:

prometheus:
  url: http://localhost:60124/api/v1
  query: /query?query=
  queryRange: /query_range?query=

common:
  regionName: pre09
  rc: http://localhost:49308/rc/resource/page/outer/query-by-tag
  cmdbApi: http://localhost:59642/topo/v3/noauth/find/instassociation/object/device
  cusInventoryApi: http://localhost:58011/hcmp/res/inventory/new
  rdbApi: http://localhost:57828/hcmp/rds/manage/resource
  cmqNodeApi: http://cmq-common.{{.Values.sys.region}}.{{.Values.sys.intranetDomain}}/inner/cmq/v1/node/state
  cmqInsApi: http://cmq-kafka-product-console.{{.Values.sys.region}}.{{.Values.sys.intranetDomain}}/inner/cmq/v1/kafka/instancenumdata
  ccosHawkeyeApi: http://localhost:56385/api/alert
  cocClusterBigScreenApi: http://localhost:51156/api/ccm/bigscreen
  ebsApi: http://localhost:52057/compute/ebs/ops/v1/volumes
  resourceTagApi: http://localhost:53166/inner/resource-tag
  ossApi: http://localhost:49173/bucket/resource/information
  efsApi: http://localhost:52244/v1.0/efs/external/share/information
